In [30]:
import warnings
warnings.filterwarnings('ignore')

In [31]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
%matplotlib inline
from matplotlib import pyplot as plt

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [33]:
# Generate bucket dictionaries
results_dict = {}
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

def model_results(model_name,y_test,y_pred):
    results_dict[model_name] = {
    'balanced_accuracy_score': balanced_accuracy_score(y_test, y_pred),
    'confusion_matrix' : confusion_matrix(y_test, y_pred),
    'classification_report_imbalanced' : pd.DataFrame(classification_report_imbalanced(y_test, y_pred, output_dict=True)).transpose().loc[['high_risk','low_risk']]
    }

# Read the CSV and Perform Basic Data Cleaning

In [34]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [35]:
# Load the data
file_path = 'LoanStats_2019Q1.csv'
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [36]:
# Dataframe with datatypes and column names
df_dtypes = pd.DataFrame({
    'column_name': df.columns,
    'dtype': df.dtypes
})
df_dtypes.index = pd.Series(range(len(df.dtypes)))
print(df_dtypes.groupby('dtype').count())
non_numerical_dtypes = df_dtypes.loc[(df_dtypes['dtype']=='object')&(df_dtypes['column_name']!='loan_status')]['column_name'].reset_index(drop=True)
non_numerical_dtypes

         column_name
dtype
float64           76
object            10

0          home_ownership
1     verification_status
2                 issue_d
3              pymnt_plan
4     initial_list_status
5            next_pymnt_d
6        application_type
7           hardship_flag
8    debt_settlement_flag
Name: column_name, dtype: object

In [37]:
# Create our features
X = df.copy().drop('loan_status',axis=1)
X = pd.get_dummies(X,columns=non_numerical_dtypes)

# Create our target
y = df['loan_status']

In [38]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [39]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=20)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [41]:
# Resample training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
# StandardScaler instance.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fitting the Standard Scaler with training data
X_scaler = scaler.fit(X_train)
#Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
# Create a BalancedRandomForest Classifier
brfc_model = BalancedRandomForestClassifier(n_estimators=150, random_state = 20)
# Fit the model
brfc_model.fit(X_train_scaled, y_train)
# Make predictions using testing data
predictions = brfc_model.predict(X_test_scaled)

In [42]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, predictions)

0.7786368613138686

In [43]:
# Display the confusion matrix
confusion_matrix(y_test, predictions)

array([[   53,    27],
       [ 1802, 15323]], dtype=int64)

In [44]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.66      0.89      0.05      0.77      0.58        80
   low_risk       1.00      0.89      0.66      0.94      0.77      0.61     17125

avg / total       0.99      0.89      0.66      0.94      0.77      0.61     17205

In [45]:
# List the features sorted in descending order by feature importance
features = sorted(zip(brfc_model.feature_importances_, X.columns), reverse=True)
features

[(0.07028251489944472, 'total_rec_prncp'),
 (0.0660595222150537, 'total_pymnt_inv'),
 (0.06195917578075834, 'total_rec_int'),
 (0.05880534188129876, 'total_pymnt'),
 (0.0483435081421817, 'last_pymnt_amnt'),
 (0.028842806381863432, 'int_rate'),
 (0.02224553764099379, 'issue_d_Jan-2019'),
 (0.018261088588041735, 'dti'),
 (0.016285278037499733, 'mo_sin_old_rev_tl_op'),
 (0.01618411752145854, 'max_bal_bc'),
 (0.016139025062779932, 'out_prncp_inv'),
 (0.01584808574471992, 'bc_util'),
 (0.015729452409237323, 'installment'),
 (0.01543838986549585, 'revol_bal'),
 (0.015380866435369548, 'issue_d_Mar-2019'),
 (0.015356401261271982, 'mo_sin_old_il_acct'),
 (0.015292506774425825, 'out_prncp'),
 (0.015179986578222077, 'annual_inc'),
 (0.015140441119216646, 'tot_hi_cred_lim'),
 (0.013958533905912597, 'avg_cur_bal'),
 (0.013794654584635859, 'bc_open_to_buy'),
 (0.01348233595005104, 'mths_since_recent_inq'),
 (0.013452893496470598, 'total_bc_limit'),
 (0.013317695980262336, 'total_bal_ex_mort'),
 (0.013307357703929512, 'all_util'),
 (0.013224642585052463, 'il_util'),
 (0.013155537129706314, 'total_il_high_credit_limit'),
 (0.013104890485918732, 'loan_amnt'),
 (0.012852167592907733, 'mths_since_rcnt_il'),
 (0.012726180347446357, 'tot_cur_bal'),
 (0.012312985889368628, 'total_rev_hi_lim'),
 (0.01155927146684345, 'total_bal_il'),
 (0.011471997358818571, 'mths_since_recent_bc'),
 (0.011455371921566976, 'num_il_tl'),
 (0.010885659144388271, 'num_rev_accts'),
 (0.010624622260606044, 'mo_sin_rcnt_rev_tl_op'),
 (0.009895613221571365, 'num_sats'),
 (0.009543080050705534, 'mo_sin_rcnt_tl'),
 (0.009512603478332826, 'acc_open_past_24mths'),
 (0.009295643982815995, 'total_acc'),
 (0.009181712476282574, 'open_acc'),
 (0.008546033169171805, 'total_rec_late_fee'),
 (0.00811983258798087, 'num_tl_op_past_12m'),
 (0.007942065362595778, 'num_bc_tl'),
 (0.007278063243570015, 'open_acc_6m'),
 (0.00721154086222193, 'num_actv_rev_tl'),
 (0.007183546307104755, 'num_bc_sats'),
 (0.0071021040763016435, 'inq_fi'),
 (0.006978640326304639, 'pct_tl_nvr_dlq'),
 (0.006975061930874792, 'open_rv_24m'),
 (0.0069597741404750085, 'next_pymnt_d_Apr-2019'),
 (0.006918470909652459, 'num_op_rev_tl'),
 (0.006768940350830628, 'open_il_24m'),
 (0.006606010127423353, 'num_actv_bc_tl'),
 (0.006573063755078856, 'num_rev_tl_bal_gt_0'),
 (0.006541070808314049, 'inq_last_12m'),
 (0.006371868460980751, 'percent_bc_gt_75'),
 (0.006119591043918994, 'open_act_il'),
 (0.005789447661973064, 'total_cu_tl'),
 (0.005689819777007886, 'issue_d_Feb-2019'),
 (0.005181084134635187, 'inq_last_6mths'),
 (0.0050544326392213835, 'mort_acc'),
 (0.004908378962661046, 'next_pymnt_d_May-2019'),
 (0.004755468068115552, 'open_il_12m'),
 (0.0047375839329698455, 'open_rv_12m'),
 (0.0038686869812049967, 'num_accts_ever_120_pd'),
 (0.0036247877380658914, 'delinq_2yrs'),
 (0.0034069472939770138, 'tot_coll_amt'),
 (0.002712213461605865, 'verification_status_Source Verified'),
 (0.0025071801053691977, 'verification_status_Verified'),
 (0.002506206320456016, 'verification_status_Not Verified'),
 (0.0025031391192336374, 'application_type_Joint App'),
 (0.0018735500596583781, 'pub_rec'),
 (0.001797320690238507, 'home_ownership_RENT'),
 (0.0017072573655230485, 'application_type_Individual'),
 (0.0014635926337609546, 'initial_list_status_w'),
 (0.0014483070430684043, 'pub_rec_bankruptcies'),
 (0.0014348832185763264, 'home_ownership_OWN'),
 (0.001146054406533652, 'home_ownership_MORTGAGE'),
 (0.001096579755500913, 'num_tl_90g_dpd_24m'),
 (0.0010203735095359705, 'initial_list_status_f'),
 (0.00027485386095200953, 'collections_12_mths_ex_med'),
 (0.00024404152955867834, 'home_ownership_ANY'),
 (0.0001626349148690812, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

In [46]:
model_results("BalancedRandomForestClassifier",y_test,predictions)
results_dict["BalancedRandomForestClassifier"]['classification_report_imbalanced']

                pre       rec       spe       f1       geo       iba      sup
high_risk  0.028571  0.662500  0.894774  0.05478  0.769927  0.579019     80.0
low_risk   0.998241  0.894774  0.662500  0.94368  0.769927  0.606556  17125.0

### Easy Ensemble AdaBoost Classifier

In [48]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
easy_ensemblec_model = EasyEnsembleClassifier(n_estimators=150, random_state = 20)
easy_ensemblec_model.fit(X_train_scaled, y_train)
predictions = easy_ensemblec_model.predict(X_test_scaled)

In [49]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, predictions)

0.9077481751824817

In [50]:
# Display the confusion matrix
confusion_matrix(y_test, predictions)

array([[   70,    10],
       [ 1019, 16106]], dtype=int64)

In [51]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.06      0.88      0.94      0.12      0.91      0.82        80
   low_risk       1.00      0.94      0.88      0.97      0.91      0.83     17125

avg / total       1.00      0.94      0.88      0.97      0.91      0.83     17205

In [52]:
model_results("EasyEnsembleClassifier",y_test,predictions)
results_dict["EasyEnsembleClassifier"]['classification_report_imbalanced']

                pre       rec       spe        f1       geo       iba      sup
high_risk  0.064279  0.875000  0.940496  0.119760  0.907157  0.817544     80.0
low_risk   0.999379  0.940496  0.875000  0.969044  0.907157  0.828324  17125.0

In [60]:
# Print Results 
for model in results_dict.keys():
    print(f"Model: {model}")
    for key, value in results_dict[model].items():
        print(f"\n{key}\n{value}")
    print('------------------------------------------------------------------------------')

Model: BalancedRandomForestClassifier

balanced_accuracy_score
0.7786368613138686

confusion_matrix
[[   53    27]
 [ 1802 15323]]

classification_report_imbalanced
                pre       rec       spe       f1       geo       iba      sup
high_risk  0.028571  0.662500  0.894774  0.05478  0.769927  0.579019     80.0
low_risk   0.998241  0.894774  0.662500  0.94368  0.769927  0.606556  17125.0
------------------------------------------------------------------------------
Model: EasyEnsembleClassifier

balanced_accuracy_score
0.9077481751824817

confusion_matrix
[[   70    10]
 [ 1019 16106]]

classification_report_imbalanced
                pre       rec       spe        f1       geo       iba      sup
high_risk  0.064279  0.875000  0.940496  0.119760  0.907157  0.817544     80.0
low_risk   0.999379  0.940496  0.875000  0.969044  0.907157  0.828324  17125.0
------------------------------------------------------------------------------